<?php

$scale5 = static fn(): array => [
    ['code' => 'MUY_BUENO', 'label' => 'Muy bueno', 'value' => 'Muy bueno'],
    ['code' => 'BUENO', 'label' => 'Bueno', 'value' => 'Bueno'],
    ['code' => 'INDIFERENTE', 'label' => 'Indiferente', 'value' => 'Indiferente'],
    ['code' => 'MALO', 'label' => 'Malo', 'value' => 'Malo'],
    ['code' => 'MUY_MALO', 'label' => 'Muy malo', 'value' => 'Muy malo'],
];

$yesNo = static fn(): array => [
    ['code' => 'SI', 'label' => 'Sí', 'value' => 'Sí'],
    ['code' => 'NO', 'label' => 'No', 'value' => 'No'],
];

return [
    'name' => 'Encuesta elecciones abril 2026',
    'slug' => 'elecciones-abril-2026',
    'description' => 'Encuesta electoral parametrizada para la provincia de Manabí, con captura pública, panel administrativo y analítica ejecutiva.',
    'status' => 'active',
    'is_public' => 1,
    'start_at' => '2026-04-04 00:00:00',
    'end_at' => '2026-04-30 23:59:59',
    'intro_title' => 'Encuesta Provincia de Manabí',
    'intro_text' => 'Su participación es confidencial. El formulario está dividido por secciones para hacerlo más ágil desde móvil o escritorio.',
    'thank_you_text' => 'Gracias. Su respuesta fue registrada correctamente.',
    'settings' => [
        'estimated_minutes' => 12,
        'theme' => 'shalom',
        'allow_multiple_submissions' => true,
    ],
    'sections' => [
        [
            'title' => 'Análisis sociodemográfico',
            'description' => 'Ubicación y perfil básico del encuestado.',
            'sort_order' => 1,
            'questions' => [
                [
                    'code' => 'Q1',
                    'prompt' => 'Cantón',
                    'question_type' => 'single_choice',
                    'is_required' => 1,
                    'sort_order' => 1,
                    'options' => [
                        ['code' => '24_DE_MAYO', 'label' => '24 de Mayo'],
                        ['code' => 'BOLIVAR', 'label' => 'Bolívar'],
                        ['code' => 'CHONE', 'label' => 'Chone'],
                        ['code' => 'EL_CARMEN', 'label' => 'El Carmen'],
                        ['code' => 'FLAVIO_ALFARO', 'label' => 'Flavio Alfaro'],
                        ['code' => 'JAMA', 'label' => 'Jama'],
                        ['code' => 'JARAMIJO', 'label' => 'Jaramijó'],
                        ['code' => 'JIPIJAPA', 'label' => 'Jipijapa'],
                        ['code' => 'JUNIN', 'label' => 'Junín'],
                        ['code' => 'MANTA', 'label' => 'Manta'],
                        ['code' => 'MONTECRISTI', 'label' => 'Montecristi'],
                        ['code' => 'OLMEDO', 'label' => 'Olmedo'],
                        ['code' => 'PAJAN', 'label' => 'Paján'],
                        ['code' => 'PEDERNALES', 'label' => 'Pedernales'],
                        ['code' => 'PICHINCHA', 'label' => 'Pichincha'],
                        ['code' => 'PORTOVIEJO', 'label' => 'Portoviejo'],
                        ['code' => 'PUERTO_LOPEZ', 'label' => 'Puerto López'],
                        ['code' => 'ROCAFUERTE', 'label' => 'Rocafuerte'],
                        ['code' => 'SAN_VICENTE', 'label' => 'San Vicente'],
                        ['code' => 'SANTA_ANA', 'label' => 'Santa Ana'],
                        ['code' => 'SUCRE', 'label' => 'Sucre'],
                        ['code' => 'TOSAGUA', 'label' => 'Tosagua'],
                    ],
                ],
                [
                    'code' => 'Q2',
                    'prompt' => 'Parroquia',
                    'question_type' => 'text',
                    'is_required' => 1,
                    'placeholder' => 'Ingrese la parroquia',
                    'sort_order' => 2,
                ],
                [
                    'code' => 'Q3',
                    'prompt' => 'Barrio',
                    'question_type' => 'text',
                    'is_required' => 1,
                    'placeholder' => 'Ingrese el barrio o sector',
                    'sort_order' => 3,
                ],
                [
                    'code' => 'Q4',
                    'prompt' => '¿Cuál es su rango de edad?',
                    'question_type' => 'single_choice',
                    'is_required' => 1,
                    'sort_order' => 4,
                    'options' => [
                        ['code' => '16_19', 'label' => '16 - 19'],
                        ['code' => '20_24', 'label' => '20 - 24'],
                        ['code' => '25_29', 'label' => '25 - 29'],
                        ['code' => '30_34', 'label' => '30 - 34'],
                        ['code' => '35_39', 'label' => '35 - 39'],
                        ['code' => '40_44', 'label' => '40 - 44'],
                        ['code' => '45_49', 'label' => '45 - 49'],
                        ['code' => '50_54', 'label' => '50 - 54'],
                        ['code' => '55_59', 'label' => '55 - 59'],
                        ['code' => '60_64', 'label' => '60 - 64'],
                        ['code' => '65_MAS', 'label' => '65 +'],
                    ],
                ],
                [
                    'code' => 'Q5',
                    'prompt' => 'Género',
                    'question_type' => 'single_choice',
                    'is_required' => 1,
                    'sort_order' => 5,
                    'options' => [
                        ['code' => 'MASCULINO', 'label' => 'Masculino'],
                        ['code' => 'FEMENINO', 'label' => 'Femenino'],
                    ],
                ],
                [
                    'code' => 'Q6',
                    'prompt' => '¿Cuál es su ocupación principal?',
                    'question_type' => 'single_choice',
                    'is_required' => 1,
                    'sort_order' => 6,
                    'options' => [
                        ['code' => 'JORNALERO', 'label' => 'Jornalero'],
                        ['code' => 'JUBILADO', 'label' => 'Jubilado'],
                        ['code' => 'SIN_OCUPACION', 'label' => 'Sin ocupación'],
                        ['code' => 'ESTUDIANTE', 'label' => 'Estudiante'],
                        ['code' => 'EMPRESARIO', 'label' => 'Empresario'],
                        ['code' => 'OBRERO_PARCIAL', 'label' => 'Obrero a tiempo parcial'],
                        ['code' => 'DESEMPLEADO', 'label' => 'Desempleado en busca de trabajo'],
                        ['code' => 'AMA_DE_CASA', 'label' => 'Ama de casa'],
                        ['code' => 'EMPLEADO_PRIVADO', 'label' => 'Empleado privado'],
                        ['code' => 'AUTONOMO', 'label' => 'Trabajador autónomo'],
                        ['code' => 'EMPLEADO_PUBLICO', 'label' => 'Empleado público'],
                    ],
                ],
                [
                    'code' => 'Q7',
                    'prompt' => '¿Cuál es el ingreso mensual de este hogar sumando todos los ingresos?',
                    'question_type' => 'single_choice',
                    'is_required' => 1,
                    'sort_order' => 7,
                    'options' => [
                        ['code' => 'SIN_INGRESOS', 'label' => 'No percibo ingresos'],
                        ['code' => 'MENOR_460', 'label' => 'Menor a 460'],
                        ['code' => '461_800', 'label' => '461 a 800 dólares'],
                        ['code' => '801_1500', 'label' => '801 a 1500 dólares'],
                        ['code' => '1501_MAS', 'label' => '1501 a más'],
                    ],
                ],
            ],
        ],
        [
            'title' => 'Problemas y coyuntura',
            'description' => 'Identificación de prioridades del país y del cantón.',
            'sort_order' => 2,
            'questions' => [
                [
                    'code' => 'Q8',
                    'prompt' => '¿Cuál cree usted que es el principal problema del país?',
                    'question_type' => 'multiple_choice',
                    'is_required' => 1,
                    'help_text' => 'Puede seleccionar varias opciones.',
                    'sort_order' => 1,
                    'options' => [
                        ['code' => 'INSEGURIDAD', 'label' => 'Inseguridad'],
                        ['code' => 'DESEMPLEO', 'label' => 'Desempleo'],
                        ['code' => 'SALUD', 'label' => 'Salud'],
                        ['code' => 'EDUCACION', 'label' => 'Educación'],
                        ['code' => 'AMBIENTAL', 'label' => 'Ambiental'],
                        ['code' => 'CORRUPCION', 'label' => 'Corrupción'],
                        ['code' => 'ENERGIA', 'label' => 'Energía eléctrica'],
                    ],
                ],
                [
                    'code' => 'Q9',
                    'prompt' => '¿Cuál cree usted que es el principal problema de su cantón?',
                    'question_type' => 'multiple_choice',
                    'is_required' => 1,
                    'help_text' => 'Puede seleccionar varias opciones.',
                    'sort_order' => 2,
                    'options' => [
                        ['code' => 'INSEGURIDAD', 'label' => 'Inseguridad'],
                        ['code' => 'DESEMPLEO', 'label' => 'Desempleo'],
                        ['code' => 'SALUD', 'label' => 'Salud'],
                        ['code' => 'EDUCACION', 'label' => 'Educación'],
                        ['code' => 'VIALIDAD', 'label' => 'Vialidad'],
                        ['code' => 'CORRUPCION', 'label' => 'Corrupción'],
                        ['code' => 'AGUA_POTABLE', 'label' => 'Agua potable'],
                    ],
                ],
            ],
        ],
        [
            'title' => 'Imagen y liderazgo político',
            'description' => 'Percepciones sobre autoridades, movimientos y posicionamiento político.',
            'sort_order' => 3,
            'questions' => [
                ['code' => 'Q10', 'prompt' => '¿Qué opina de la gestión del presidente Daniel Noboa?', 'question_type' => 'rating', 'is_required' => 1, 'sort_order' => 1, 'options' => $scale5()],
                ['code' => 'Q11', 'prompt' => '¿Qué imagen tiene del presidente Daniel Noboa?', 'question_type' => 'rating', 'is_required' => 1, 'sort_order' => 2, 'options' => $scale5()],
                ['code' => 'Q12', 'prompt' => '¿Usted le cree al presidente Daniel Noboa?', 'question_type' => 'single_choice', 'is_required' => 1, 'sort_order' => 3, 'options' => $yesNo()],
                ['code' => 'Q13', 'prompt' => '¿Qué opina de la gestión del prefecto Leonardo Orlando?', 'question_type' => 'rating', 'is_required' => 1, 'sort_order' => 4, 'options' => $scale5()],
                ['code' => 'Q14', 'prompt' => '¿Qué imagen tiene del prefecto Leonardo Orlando?', 'question_type' => 'rating', 'is_required' => 1, 'sort_order' => 5, 'options' => $scale5()],
                ['code' => 'Q15', 'prompt' => '¿Usted le cree al prefecto Leonardo Orlando?', 'question_type' => 'single_choice', 'is_required' => 1, 'sort_order' => 6, 'options' => $yesNo()],
                ['code' => 'Q16', 'prompt' => '¿Ud considera que Leonardo Orlando, una vez terminado su segundo mandato como Prefecto de Manabí, debe seguir en la política?', 'question_type' => 'single_choice', 'is_required' => 1, 'sort_order' => 7, 'options' => $yesNo()],
                [
                    'code' => 'Q17',
                    'prompt' => 'Si respondió que sí en la pregunta anterior, ¿qué dignidad considera usted que Leonardo Orlando debería ocupar?',
                    'question_type' => 'single_choice',
                    'is_required' => 0,
                    'sort_order' => 8,
                    'visibility_rules' => [['question_code' => 'Q16', 'operator' => 'equals', 'value' => 'SI']],
                    'options' => [
                        ['code' => 'ALCALDE', 'label' => 'Alcalde'],
                        ['code' => 'ASAMBLEISTA', 'label' => 'Asambleísta'],
                        ['code' => 'PRESIDENTE', 'label' => 'Presidente de la República'],
                    ],
                ],
                [
                    'code' => 'Q18',
                    'prompt' => '¿Cree usted que Leonardo Orlando debe formar su propio partido/movimiento?',
                    'question_type' => 'single_choice',
                    'is_required' => 1,
                    'sort_order' => 9,
                    'options' => [
                        ['code' => 'SI', 'label' => 'Sí'],
                        ['code' => 'SEGUIR_RC', 'label' => 'No, debe seguir formando parte de la RC'],
                        ['code' => 'ALIARSE_OTRO', 'label' => 'No, debe aliarse con otro partido existente'],
                    ],
                ],
                ['code' => 'Q19', 'prompt' => '¿Cree usted que Leonardo Orlando debe formar alianzas con Daniel Noboa?', 'question_type' => 'single_choice', 'is_required' => 1, 'sort_order' => 10, 'options' => $yesNo()],
                ['code' => 'Q20', 'prompt' => '¿Qué imagen tiene de Luisa González?', 'question_type' => 'rating', 'is_required' => 1, 'sort_order' => 11, 'options' => $scale5()],
                ['code' => 'Q21', 'prompt' => '¿Usted le cree a Luisa González?', 'question_type' => 'single_choice', 'is_required' => 1, 'sort_order' => 12, 'options' => $yesNo()],
                [
                    'code' => 'Q22',
                    'prompt' => 'Según usted, ¿cuál de las siguientes figuras representa mejor al correísmo en Manabí?',
                    'question_type' => 'single_choice',
                    'is_required' => 1,
                    'sort_order' => 13,
                    'options' => [
                        ['code' => 'JAIME_ESTRADA', 'label' => 'Jaime Estrada'],
                        ['code' => 'JUAN_JOSE_PENA', 'label' => 'Juan José Peña'],
                        ['code' => 'LEONARDO_ORLANDO', 'label' => 'Leonardo Orlando'],
                        ['code' => 'LUISA_GONZALEZ', 'label' => 'Luisa González'],
                    ],
                ],
                [
                    'code' => 'Q23',
                    'prompt' => 'Ud se considera:',
                    'question_type' => 'single_choice',
                    'is_required' => 1,
                    'sort_order' => 14,
                    'options' => [
                        ['code' => 'CORREISTA', 'label' => 'Correísta'],
                        ['code' => 'ANTICORREISTA', 'label' => 'Anticorreísta'],
                        ['code' => 'INDIFERENTE', 'label' => 'Indiferente'],
                    ],
                ],
                [
                    'code' => 'Q24',
                    'prompt' => 'O se considera:',
                    'question_type' => 'single_choice',
                    'is_required' => 1,
                    'sort_order' => 15,
                    'options' => [
                        ['code' => 'NOBOISTA', 'label' => 'Noboísta'],
                        ['code' => 'ANTINOBOISTA', 'label' => 'Antinoboísta'],
                        ['code' => 'INDIFERENTE', 'label' => 'Indiferente'],
                    ],
                ],
                [
                    'code' => 'Q25',
                    'prompt' => '¿Con qué partido o movimiento político se identifica más?',
                    'question_type' => 'single_choice',
                    'is_required' => 1,
                    'sort_order' => 16,
                    'options' => [
                        ['code' => 'CENTRO_DEMOCRATICO', 'label' => 'Centro Democrático'],
                        ['code' => 'UNIDAD_POPULAR', 'label' => 'Unidad Popular'],
                        ['code' => 'PSP', 'label' => 'Partido Sociedad Patriótica'],
                        ['code' => 'PUEBLO_IGUALDAD', 'label' => 'Pueblo, Igualdad'],
                        ['code' => 'RC5', 'label' => 'Revolución Ciudadana'],
                        ['code' => 'PSC', 'label' => 'PSC'],
                        ['code' => 'ADN', 'label' => 'ADN'],
                        ['code' => 'AVANZA', 'label' => 'Avanza'],
                        ['code' => 'ID', 'label' => 'Izquierda Democrática'],
                        ['code' => 'AMIGO', 'label' => 'Amigo'],
                        ['code' => 'PARTIDO_SOCIALISTA', 'label' => 'Partido Socialista'],
                        ['code' => 'PACHAKUTIK', 'label' => 'Pachakutik'],
                        ['code' => 'RETO', 'label' => 'Reto'],
                        ['code' => 'SUMA', 'label' => 'SUMA'],
                        ['code' => 'CONSTRUYE', 'label' => 'Construye'],
                        ['code' => 'CREO', 'label' => 'CREO'],
                        ['code' => 'DEMOCRACIA_SI', 'label' => 'Democracia Sí'],
                        ['code' => 'NO_SABE', 'label' => 'No sabe / No contesta'],
                        ['code' => 'NULO', 'label' => 'Nulo'],
                        ['code' => 'BLANCO', 'label' => 'Blanco'],
                    ],
                ],
            ],
        ],
        [
            'title' => 'Elecciones seccionales',
            'description' => 'Intención de voto para prefectura y alcaldía.',
            'sort_order' => 4,
            'questions' => [
                [
                    'code' => 'Q26',
                    'prompt' => 'Si las elecciones a Prefecto/a fueran hoy, por quién votaría Papeleta (A)',
                    'question_type' => 'single_choice',
                    'is_required' => 1,
                    'sort_order' => 1,
                    'options' => [
                        ['code' => 'JUAN_JOSE_PENA', 'label' => 'Juan José Peña - Si Podemos'],
                        ['code' => 'AGUSTIN_CASANOVA', 'label' => 'Agustín Casanova - Caminantes'],
                        ['code' => 'ABEL_GOMEZ', 'label' => 'Abel Gómez - ADN'],
                        ['code' => 'LEONARDO_RODRIGUEZ', 'label' => 'Leonardo Rodríguez'],
                        ['code' => 'NO_SABE', 'label' => 'No sabe, no ha decidido'],
                        ['code' => 'NULO', 'label' => 'Nulo/Ninguno'],
                    ],
                ],
                [
                    'code' => 'Q27',
                    'prompt' => 'Si las elecciones a Prefecto/a fueran hoy, por quién votaría Papeleta (B)',
                    'question_type' => 'single_choice',
                    'is_required' => 1,
                    'sort_order' => 2,
                    'options' => [
                        ['code' => 'JAIME_ESTRADA', 'label' => 'Jaime Estrada - Si Podemos'],
                        ['code' => 'AGUSTIN_CASANOVA', 'label' => 'Agustín Casanova - Caminantes'],
                        ['code' => 'CARLOS_LUIS_ANDRADE', 'label' => 'Carlos Luis Andrade - ADN'],
                        ['code' => 'LEONARDO_ORLANDO', 'label' => 'Candidato Leonardo Orlando'],
                        ['code' => 'LEONARDO_RODRIGUEZ', 'label' => 'Leonardo Rodríguez'],
                        ['code' => 'NO_SABE', 'label' => 'No sabe, no ha decidido'],
                        ['code' => 'NULO', 'label' => 'Nulo/Ninguno'],
                    ],
                ],
                [
                    'code' => 'Q28',
                    'prompt' => 'Si las elecciones a Alcalde/sa fueran hoy, por quién votaría Papeleta (A)',
                    'question_type' => 'single_choice',
                    'is_required' => 0,
                    'sort_order' => 3,
                    'visibility_rules' => [['question_code' => 'Q1', 'operator' => 'equals', 'value' => 'PORTOVIEJO']],
                    'options' => [
                        ['code' => 'LEONARDO_ORLANDO', 'label' => 'Leonardo Orlando - Si Podemos'],
                        ['code' => 'JAVIER_PINCAY', 'label' => 'Javier Pincay - Avanza-Machete'],
                        ['code' => 'MARIA_JOSE_FERNANDEZ', 'label' => 'María José Fernández - ADN'],
                        ['code' => 'LEONEL_MUNOZ', 'label' => 'Leonel Muñoz'],
                        ['code' => 'OTRO', 'label' => 'Otro, alguien nuevo'],
                        ['code' => 'NO_SABE', 'label' => 'No sabe, no ha decidido'],
                        ['code' => 'NULO', 'label' => 'Nulo/Ninguno'],
                    ],
                ],
                [
                    'code' => 'Q29',
                    'prompt' => 'Si las elecciones a Alcalde/sa fueran hoy, por quién votaría Papeleta (B)',
                    'question_type' => 'single_choice',
                    'is_required' => 0,
                    'sort_order' => 4,
                    'visibility_rules' => [['question_code' => 'Q1', 'operator' => 'equals', 'value' => 'PORTOVIEJO']],
                    'options' => [
                        ['code' => 'CANDIDATO_SI_PODEMOS', 'label' => 'Candidato Si Podemos'],
                        ['code' => 'JAVIER_PINCAY', 'label' => 'Javier Pincay - ADN'],
                        ['code' => 'CANDIDATO_LEONARDO_ORLANDO', 'label' => 'Candidato de Leonardo Orlando'],
                        ['code' => 'CANDIDATO_AGUSTIN_CASANOVA', 'label' => 'Candidato de Agustín Casanova - Caminantes'],
                        ['code' => 'LEONEL_MUNOZ', 'label' => 'Leonel Muñoz'],
                        ['code' => 'MARIA_JOSE_FERNANDEZ', 'label' => 'María José Fernández - ADN'],
                        ['code' => 'OTRO', 'label' => 'Otro, alguien nuevo'],
                        ['code' => 'NO_SABE', 'label' => 'No sabe, no ha decidido'],
                        ['code' => 'NULO', 'label' => 'Nulo/Ninguno'],
                    ],
                ],
            ],
        ],
        [
            'title' => 'Análisis de la Asamblea Nacional e instituciones',
            'description' => 'Percepción de instituciones, autoridades locales y organizaciones políticas.',
            'sort_order' => 5,
            'questions' => [
                ['code' => 'Q31', 'prompt' => '¿Qué imagen tiene de la alcaldía de su ciudad?', 'question_type' => 'rating', 'is_required' => 1, 'sort_order' => 1, 'options' => $scale5()],
                ['code' => 'Q32', 'prompt' => '¿Qué imagen tiene del alcalde de su ciudad?', 'question_type' => 'rating', 'is_required' => 1, 'sort_order' => 2, 'options' => $scale5()],
                ['code' => 'Q33', 'prompt' => '¿Qué imagen tiene de la Prefectura?', 'question_type' => 'rating', 'is_required' => 1, 'sort_order' => 3, 'options' => $scale5()],
                ['code' => 'Q34', 'prompt' => '¿Qué imagen tiene del prefecto de la provincia?', 'question_type' => 'rating', 'is_required' => 1, 'sort_order' => 4, 'options' => $scale5()],
                ['code' => 'Q35', 'prompt' => '¿Qué imagen tiene del partido político RC5?', 'question_type' => 'rating', 'is_required' => 1, 'sort_order' => 5, 'options' => $scale5()],
                ['code' => 'Q36', 'prompt' => '¿Qué imagen tiene del partido político ADN 7?', 'question_type' => 'rating', 'is_required' => 1, 'sort_order' => 6, 'options' => $scale5()],
            ],
        ],
        [
            'title' => 'Análisis de personajes y medios',
            'description' => 'Matriz de conocimiento político y hábitos informativos.',
            'sort_order' => 6,
            'questions' => [
                [
                    'code' => 'Q41',
                    'prompt' => 'Dígame su opinión acerca de las siguientes personas.',
                    'question_type' => 'matrix',
                    'is_required' => 1,
                    'sort_order' => 1,
                    'settings' => [
                        'matrix' => [
                            'rows' => [
                                ['code' => 'DANIEL_NOBOA', 'label' => 'Daniel Noboa'],
                                ['code' => 'LUISA_GONZALEZ', 'label' => 'Luisa González'],
                                ['code' => 'AQUILES_ALVAREZ', 'label' => 'Aquiles Álvarez'],
                                ['code' => 'MARCELA_AGUINAGA', 'label' => 'Marcela Aguiñaga'],
                                ['code' => 'LEONARDO_ORLANDO', 'label' => 'Leonardo Orlando'],
                                ['code' => 'PAOLA_PABON', 'label' => 'Paola Pabón'],
                                ['code' => 'JEAN_TOPIC', 'label' => 'Jean Topic'],
                            ],
                            'dimensions' => [
                                ['code' => 'KNOWS', 'label' => '¿Conoce al candidato?', 'options' => $yesNo()],
                                ['code' => 'PERCEPTION', 'label' => '¿Qué percepción tiene?', 'options' => [
                                    ['code' => 'BUENA', 'label' => 'Buena'],
                                    ['code' => 'NEUTRA', 'label' => 'Neutra'],
                                    ['code' => 'MALA', 'label' => 'Mala'],
                                ]],
                                ['code' => 'BELIEVES', 'label' => '¿Cree en el candidato?', 'options' => [
                                    ['code' => 'SI', 'label' => 'Sí'],
                                    ['code' => 'NO', 'label' => 'No'],
                                    ['code' => 'INDIFERENTE', 'label' => 'Indiferente'],
                                ]],
                                ['code' => 'WOULD_VOTE', 'label' => '¿Votaría por él?', 'options' => $yesNo()],
                                ['code' => 'ASSOCIATES', 'label' => '¿Con qué figura política lo asocia?', 'options' => [
                                    ['code' => 'DANIEL_NOBOA', 'label' => 'Daniel Noboa'],
                                    ['code' => 'RAFAEL_CORREA', 'label' => 'Rafael Correa'],
                                    ['code' => 'JAIME_NEBOT', 'label' => 'Jaime Nebot'],
                                    ['code' => 'GUILLERMO_LASSO', 'label' => 'Guillermo Lasso'],
                                ]],
                            ],
                        ],
                    ],
                ],
                [
                    'code' => 'Q42',
                    'prompt' => '¿Por qué medio usted se entera de las noticias?',
                    'question_type' => 'single_choice',
                    'is_required' => 1,
                    'sort_order' => 2,
                    'options' => [
                        ['code' => 'PERIODICO', 'label' => 'Periódico'],
                        ['code' => 'REDES_SOCIALES', 'label' => 'Redes sociales'],
                        ['code' => 'TELEVISION', 'label' => 'Televisión'],
                        ['code' => 'RADIO', 'label' => 'Radio'],
                        ['code' => 'AMIGOS_VECINOS', 'label' => 'Amigos o vecinos'],
                    ],
                ],
                [
                    'code' => 'Q43',
                    'prompt' => 'Si utiliza redes sociales, ¿qué redes usa?',
                    'question_type' => 'multiple_choice',
                    'is_required' => 0,
                    'sort_order' => 3,
                    'visibility_rules' => [['question_code' => 'Q42', 'operator' => 'equals', 'value' => 'REDES_SOCIALES']],
                    'options' => [
                        ['code' => 'X', 'label' => 'X (antes Twitter)'],
                        ['code' => 'FACEBOOK', 'label' => 'Facebook'],
                        ['code' => 'INSTAGRAM', 'label' => 'Instagram'],
                        ['code' => 'TIKTOK', 'label' => 'TikTok'],
                        ['code' => 'YOUTUBE', 'label' => 'YouTube'],
                    ],
                ],
            ],
        ],
    ],
];
